### ISSUE TITLE
Problem with removing quotes on strings

### ISSUE THREAD

**Issue by wizarden1** [endaft/action-yamler#166]
**Configuration:**
```
 with:
    file: /home/runner/work/experimental/experimental/compose-dev.yaml
    path: appVersion
    set: 1.1.1
    get: true
    append: false
    flat: false
```
**Source yaml file:**
```
services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
testing:
  value: "20"
  Value2: "Off"
appVersion: 1.0.0
```
**Result yaml file:**
```
services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
testing:
  value: "20"
  Value2: Off
appVersion: 1.1.1
```
The main problem of that, in helm "Off" - is string, but Off - is boolean
So we get hidden type conversation.
